### ISSUE TITLE
review：推荐使用异步组件

### ISSUE THREAD

**Issue by 643104191** [Wenswell/fresh-mart#4]
https://github.com/Wenswell/fresh-mart/blob/62ab2734691935ed5a89d7c8e81f40c6bfd68e3e/src/router/index.js#L4-L6C4

使用`import('path/to/page')`代替`import`,为什么/有什么好处可自行了解

**Comment by Wenswell** [comment]
#12 中解决

### 使用[异步组件](https://v2.cn.vuejs.org/v2/guide/components-dynamic-async.html#:~:text=%E5%BD%93%E4%BD%BF%E7%94%A8%E5%B1%80%E9%83%A8%E6%B3%A8%E5%86%8C%E7%9A%84%E6%97%B6%E5%80%99%EF%BC%8C%E4%BD%A0%E4%B9%9F%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E6%8F%90%E4%BE%9B%E4%B8%80%E4%B8%AA%E8%BF%94%E5%9B%9E%20Promise%20%E7%9A%84%E5%87%BD%E6%95%B0%EF%BC%9A)的优势

1. **避免命名冲突**

使用`import('./page')`时,总是导入一个匿名函数,不会与其他变量冲突。

而使用`import './page'`时,`page`导入的对象会暴露到当前模块中,有可能与其他导入或变量造成命名冲突。

2. **按需加载**

使用`import('./page')`时,webpack 会将其编译为一个函数,只有实际使用时才会加载。

而`import page`会实现静态导入,编译时就执行导入。

3. **便于拆分**

使用`import('./page/LoginIndex')`时,可以更灵活地拆分路由组件。
