### ISSUE TITLE
review：尝试使用css实现登录/注册的样式，而不是使用图片

### ISSUE THREAD

**Issue by 643104191** [Wenswell/fresh-mart#5]
https://github.com/Wenswell/fresh-mart/blob/62ab2734691935ed5a89d7c8e81f40c6bfd68e3e/src/views/LoginRegister/LoginIndex.vue#L7-L17
https://github.com/Wenswell/fresh-mart/blob/62ab2734691935ed5a89d7c8e81f40c6bfd68e3e/src/views/LoginRegister/RegisterIndex.vue#L7-L17

**Comment by Wenswell** [comment]
#10 中完成
