### ISSUE TITLE
review：尽可能不要影响第三方库样式

### ISSUE THREAD

**Issue by 643104191** [Wenswell/fresh-mart#6]
https://github.com/Wenswell/fresh-mart/blob/62ab2734691935ed5a89d7c8e81f40c6bfd68e3e/src/views/LoginRegister/LoginIndex.vue#LL101C1-L101C1

https://github.com/Wenswell/fresh-mart/blob/62ab2734691935ed5a89d7c8e81f40c6bfd68e3e/src/views/LoginRegister/LoginIndex.vue#L106

**Comment by Wenswell** [comment]
#10 中解决，后续继续注意
